package eu.sia.easyway.groovy.reproducer.runnable;

import java.util.UUID;

import org.codehaus.groovy.runtime.InvokerHelper;

import groovy.lang.Binding;
import groovy.lang.GroovyClassLoader;
import groovy.lang.Script;

public class AutogeneratedScriptRunnerSameClassLoaderOom implements Runnable {
	
	private final GroovyClassLoader gcl;
	
	public AutogeneratedScriptRunnerSameClassLoaderOom(GroovyClassLoader gcl) {
		this.gcl = gcl;
	}
	
	@Override
	public void run() {
		String script = "String a = \"" + UUID.randomUUID().toString() + "\"";
		Class<?> c = gcl.parseClass(script);
		Script s = InvokerHelper.createScript(c, new Binding());
		s.run();
	}
}
