package com.giof71.groovy.reproducer.runnable;

import groovy.lang.Script;

public class AutogeneratedCachedScriptRunner implements Runnable {

	private final ScriptRandomizer randomizer;
	private final ScriptCache scriptCache;
	
	public AutogeneratedCachedScriptRunner(ScriptRandomizer randomizer, ScriptCache scriptCache) {
		this.randomizer = randomizer;
		this.scriptCache = scriptCache;
	}
	
	@Override
	public void run() {
		Script s = scriptCache.getCompiled(randomizer.get());
		s.run();
	}
}
